# Generated by Django 3.0.2 on 2020-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200209_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
