# Generated by Django 3.0.2 on 2020-02-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200209_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('a', 'Available'), ('o', 'On loan'), ('m', 'Maintenance')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
