# Generated by Django 3.0.2 on 2020-02-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200212_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan'), ('m', 'Maintenance'), ('r', 'Reserved'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
