# Generated by Django 3.0.2 on 2020-02-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200212_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan'), ('r', 'Reserved'), ('m', 'Maintenance'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
