# Generated by Django 3.0.2 on 2020-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20200218_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('o', 'On loan'), ('m', 'Maintenance'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
