# Generated by Django 3.0.2 on 2020-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20200219_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan'), ('r', 'Reserved'), ('m', 'Maintenance'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
