# Generated by Django 3.0.2 on 2020-02-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_auto_20200223_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('r', 'Reserved'), ('m', 'Maintenance'), ('o', 'On loan')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
